<!-- ...................................................................... -->
<!-- SuikaWiki/0.9 Simple Documentation Format Vocabulary 2.9
             Metainformational Module ..................................... -->
<!-- file: sw09-metainfo.mod
     
     This is a markup vocabulary used in SuikaWiki/0.9 XML representation.
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T05:34:54+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "**work-in-progress**sw09-metainfo.mod"
     
     ...................................................................... -->

<!-- Metainformational

       parameter, value
-->

<!-- parameter: Document parameter ..................... -->

<!ENTITY % sw09.parameter.element "INCLUDE">
<![%sw09.parameter.element;[
<!ENTITY % sw09.parameter.content "(%sw09.value.qname;)*">
<!ENTITY % sw09.parameter.qname "parameter">
<!ENTITY % sw09.parameter.tagmin.start "-">
<!ENTITY % sw09.parameter.tagmin.end "-">
<![%sgml.tag.minimizable;[
<!ENTITY % sw09.parameter.tagmin "%sw09.parameter.tagmin.start; %sw09.parameter.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % sw09.parameter.tagmin "">
<!ELEMENT %sw09.parameter.qname; %sw09.parameter.tagmin; %sw09.parameter.content;>
<!-- end of sw09.parameter.element -->]]>

<!ENTITY % sw09.parameter.attlist "INCLUDE">
<![%sw09.parameter.attlist;[
<!ATTLIST %sw09.parameter.qname;
	name	%sw09.name.datatype;	#REQUIRED
	%sw09.common.attrib;>
<!-- end of sw09.parameter.attlist -->]]>

<!-- value: A parameter value. ......................... -->

<!ENTITY % sw09.value.element "INCLUDE">
<![%sw09.value.element;[
<!ENTITY % sw09.value.content "(#PCDATA|%Inline.mix;)*">
<!ENTITY % sw09.value.qname "value">
<!ENTITY % sw09.value.tagmin.start "-">
<!ENTITY % sw09.value.tagmin.end "-">
<![%sgml.tag.minimizable;[
<!ENTITY % sw09.value.tagmin "%sw09.value.tagmin.start; %sw09.value.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % sw09.value.tagmin "">
<!ELEMENT %sw09.value.qname; %sw09.value.tagmin; %sw09.value.content;>
<!-- end of sw09.value.element -->]]>

<!ENTITY % sw09.value.attlist "INCLUDE">
<![%sw09.value.attlist;[
<!ATTLIST %sw09.value.qname;
	%sw09.common.attrib;>
<!-- end of sw09.value.attlist -->]]>


<!-- end of sw09-metainfo.mod -->
