<!-- ...................................................................... -->
<!-- SuikaWiki/0.9 Simple Documentation Format Vocabulary 2.9
             Datatypes Module ............................................. -->
<!-- file: sw09-datatype.mod
     
     This is a markup vocabulary used in SuikaWiki/0.9 XML representation.
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T05:34:54+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "**work-in-progress**sw09-datatype.mod"
     
     ...................................................................... -->

<!-- Datatypes

     This module defines containers for the datatypes.
-->

<!-- URI Reference -->
<!ENTITY % URI.datatype "CDATA">

<!ENTITY % sw09.name.datatype "CDATA">

<!ENTITY % sw09.entity-name.datatype "CDATA">

<!ENTITY % sw09.form-name.datatype "CDATA">

<!ENTITY % sw09.anchor-number.datatype "CDATA">

<!ENTITY % sw09.class-list.datatype "CDATA">


<!-- end of sw09-datatype.mod -->
